import fs from 'node:fs';import {segmentClaims,validateSegments} from '../../tools/segment_claims.mjs';import {findNumbers} from '../../tools/check_claims.mjs';
const dir='review-evidence/auto20261010-t8-q08351';const pages=['docs/senpou-futan/index.html','docs/column/senpou-futan-3hoshiki/index.html','docs/column/kumimodoshi/index.html'];const results=[],fixes=[];
const source=(file,bands)=>{const lines=fs.readFileSync(`${dir}/corpus/${file}`,'utf8').split(/\r?\n/);return {corpus_ref:`corpus/${file}:${bands}`,snapshot_ref:`${dir}/corpus/${file}:${bands}`,source_url:lines[0].replace('出典: ',''),source_quote:bands.split(',').flatMap(b=>{const n=b.split('-').map(Number);return lines.slice(n[0]-1,n.at(-1));}).join('\n')};};
for(const page of pages){
 const slug=page.split('/').at(-2),lp=page.replace(/^docs\//,'claims/').replace(/\/index.html$/,'.json');const ledger=JSON.parse(fs.readFileSync(lp));const before=segmentClaims(fs.readFileSync(`${dir}/${slug}-before.html`,'utf8'),page),after=segmentClaims(fs.readFileSync(page,'utf8'),page),om=new Map(before.map(u=>[u.id,u])),nm=new Map(after.map(u=>[u.id,u]));const original=validateSegments(before,ledger);const fresh=after.filter(u=>!om.has(u.id)||om.get(u.id).text_hash!==u.text_hash||om.get(u.id).context_hash!==u.context_hash);const freshIds=new Set(fresh.map(u=>u.id));
 for(const c of ledger.claims)c.covers=(c.covers||[]).filter(id=>nm.has(id)&&!freshIds.has(id));
 ledger.nonclaims=(ledger.nonclaims||[]).filter(n=>nm.has(n.id)&&!freshIds.has(n.id));ledger.verified=(ledger.verified||[]).filter(v=>nm.get(v.id)?.text_hash===v.text_hash&&!freshIds.has(v.id));
 for(const u of fresh){let file='www_bk_mufg_jp_tesuuryou_furikomi_html.txt',bands='9-132,196-230',exceptions='三菱UFJダイレクトの当行宛0円、三菱UFJ信託/auじぶん宛は当行他店扱い、メインバンク プラス無料優遇を除く。電話は別区分、OTP利用登録が必要。手数料を含む方式30,154〜30,219円は受付不可。法人BizSTATIONの同行宛110/330円は別区分。';
  if(u.text.includes('ゆうちょ')){file='www_jp_bank_japanpost_jp_direct_pc_price_dr_pc_pr_index_html.txt';bands='29-68';exceptions='同行宛は月5回無料（アプリと合算）・以降100円、利用口座間は本人同一名義/同一ID登録で月1,000回以降100円。非居住者関連3,000円、他行の非居住者宛は所定窓口のみ、受入明細票送付100円、税込。';}
  else if(u.text.includes('りそな')){file='www_resonabank_co_jp_direct_service_tesuryo_html.txt';bands='14-49';exceptions='同一支店/りそなグループ本支店宛0円、グループはりそな/埼玉りそな/関西みらい/みなと。ルビー月3回82円、ダイヤ月3回0円。ATM/窓口は別区分。';}
  else if(u.text.includes('千葉')){file='www_chibabank_co_jp_kinri_fee_transfer.txt';bands='64-107';exceptions='個人マイアクセスは同一店内/本支店宛無料。法人EBは同一店無料・本支店110/330円、他行電信385/550円。アプリ/ATM等は別経路。同一店内定義・窓口ATMの店舗内店舗の例外は他行ネットの対象外。';}
  else if(u.text.includes('三井住友')){file='www_smbc_co_jp_hojin_fee_furikomi_html.txt';bands='6-79';exceptions='法人Web21エキスパート等の一般他行495/660円、同一店110/220円、本支店220/440円。ライト別料金・1日300万円まで、給与賞与EBも別区分（他行330円）。媒体持込/振込振替含む。';}
  ledger.claims.push({id:`t8q08351-cross-${u.id}`,text:u.text,numbers:[...findNumbers(u.text)],applies:'2026年9月30日取得の銀行正本。掲載サービスの通常料金。',scope:'この単位の銀行・対象者・宛先・サービス・金額帯。'+u.text,exceptions:[exceptions],covers:[u.id],...source(file,bands),status:'repairer_checked_pending_independent_review'});
  fixes.push({issue:'料金表・逆引きの宛先と経路限定（横展開）',page,old_id:null,kind:'add_condition',new_id:u.id});
 }
 ledger.checked='2026-10-10';fs.writeFileSync(lp,JSON.stringify(ledger,null,2)+'\n');const final=validateSegments(after,ledger);results.push({page,before:{total:original.total,covered:original.covered,verified:original.verified,nonclaims:original.nonclaims,unprocessed:original.unprocessed},after:{total:final.total,covered:final.covered,verified:final.verified,nonclaims:final.nonclaims,unprocessed:final.unprocessed},changed_units:fresh.length});fs.writeFileSync(`${dir}/${slug}-segments-after.json`,JSON.stringify(after,null,2)+'\n');
}
fs.writeFileSync(`${dir}/cross-page-coverage.json`,JSON.stringify(results,null,2)+'\n');const rp='/Users/masahiroyasu/Scripts/keiri-commander/runs/review-loop/auto20261010/t8-q08351/fix-kinds.json',k=JSON.parse(fs.readFileSync(rp));k.fixes.push(...fixes);fs.writeFileSync(rp,JSON.stringify(k,null,2)+'\n');fs.writeFileSync(`${dir}/fix-kinds.json`,JSON.stringify(k,null,2)+'\n');console.log(results);
