import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {JSDOM} from 'jsdom';
import {monthPair, cleanMonths} from '../docs/assets/monthly_checklist.js';
import {favoriteIDs, readJSON, writeJSON, recordUse, trackRetention, USAGE_KEY} from '../docs/assets/retention.js';
import {highlightKeyword} from '../docs/assets/keyword_highlight.js';
import {validCondition} from '../docs/assets/payday_store.js';
import {toICS} from '../docs/assets/payday_core.js';
import {search} from '../docs/assets/qa_search.js';
assert.deepEqual(monthPair(new Date('2026-12-31T14:59:59Z')),['2026-12','2027-01']);
assert.deepEqual(monthPair(new Date('2026-12-31T15:00:00Z')),['2027-01','2027-02']);
assert.deepEqual(cleanMonths({version:1,months:{'2026-09':['records','records','company'], '2026-13':['records']}}),{'2026-09':['records']});
assert.deepEqual(favoriteIDs(['yukyu','company name','yukyu','gensen-choshu']),['yukyu','gensen-choshu']);
const dom=new JSDOM('',{url:'https://keiri-tools.com/'});globalThis.window=dom.window;const events=[];window.gtag=(...a)=>events.push(a);
assert(writeJSON('test',[]));window.localStorage.setItem('test','{bad');assert.equal(readJSON('test',[]).ok,false);
recordUse('conditions','yukyu',{baseline:true,day:'2026-09-25'});recordUse('conditions','yukyu',{day:'2026-09-26'});recordUse('conditions','yukyu',{day:'2026-09-26'});
assert.equal(events.filter(e=>e[1]==='retention_reuse').length,1,'one event per different day after real use');
trackRetention('retention_save','conditions','private company','save');assert.equal(events.length,1);
for(const e of events)assert.deepEqual(Object.keys(e[2]).sort(),['action','feature','retention_version','tool']);
Object.defineProperty(window,'localStorage',{get(){throw Error('denied');}});assert.equal(writeJSON('test',[]),false);assert.equal(readJSON('test',[]).ok,false);assert.doesNotThrow(()=>recordUse('conditions','yukyu'));
delete globalThis.window;dom.window.close();
assert(validCondition({label:'旧保存',cond:{closing:20,offsetMonths:1,payday:10,adjust:'prev'}}));
assert(!validCondition({label:'bad',cond:{closing:20,offsetMonths:1,payday:10,adjust:'[injection]'}}));
const ics=toICS([{payIso:'2026-10-09',periodFrom:'2026-08-21',periodTo:'2026-09-20'}],'会社\nURL:https://private.invalid');
assert(ics.includes('\r\nURL:https://keiri-tools.com/shiharai-site/\r\n'));
assert(!ics.includes('\r\nURL:https://private.invalid'));assert(ics.replace(/\r\n /g,'').includes('自動更新されません'));assert(ics.includes('DTSTART;VALUE=DATE:20261009'));assert(ics.includes('DTSTAMP:'));assert(ics.split('\r\n').every(line=>Buffer.byteLength(line)<=75),'UTF-8 ICS folding');
assert.equal(highlightKeyword('INPIT','IT'),'INP<mark>IT</mark>');
assert.equal(highlightKeyword('<script>IT & IT</script>','IT'),'&lt;script&gt;<mark>IT</mark> &amp; <mark>IT</mark>&lt;/script&gt;');
assert.equal(highlightKeyword('x[a]','[a]'),'x<mark>[a]</mark>');
const index=JSON.parse(readFileSync(new URL('../docs/assets/qa_index.json',import.meta.url)));
for(const[q,url]of[['源泉徴収','/gensen-choshu/'],['社会保険料','/shakai-hoken/'],['源泉徴収票 書き方','/gensen-hyo/']])assert.equal(search(index,q).results[0].url,url,q);
assert(!search(index,'宇宙旅行の方法').matched);assert(search(index,'オルカン').results.every(x=>x.type==='article'));
assert(index.find(e=>e.url==='/gensen-choshu/').summary.length<60);
execFileSync(process.execPath,['tools/gen_retention_updates.mjs','--check'],{cwd:new URL('../',import.meta.url),stdio:'pipe'});
const xml=readFileSync(new URL('../docs/updates.xml',import.meta.url),'utf8'), feed=new JSDOM(xml,{contentType:'text/xml'}).window.document;
const records=JSON.parse(readFileSync(new URL('../docs/assets/retention_updates.json',import.meta.url),'utf8'));
for(const [i,item] of [...feed.querySelectorAll('item')].entries()) {
 assert.equal(item.querySelector('pubDate').textContent,new Date(records[i].recordedAt).toUTCString(),'RSS uses fixed record time');
 assert(item.querySelector('description').textContent.includes(records[i].effectiveDate),'RSS effective date');
 assert(item.querySelector('description').textContent.includes(records[i].source),'RSS official source');
 assert.equal(item.querySelector('guid').textContent,'keiri-tools:'+records[i].id);
}
assert.equal(feed.querySelectorAll('parsererror').length,0);assert.equal(feed.querySelectorAll('item').length,2);assert(feed.querySelector('description').textContent.includes('適用日'));
for (const match of readFileSync(new URL('../docs/assets/monthly_checklist.js',import.meta.url),'utf8').matchAll(/['"](\/(?:[a-z0-9-]+\/)+)(?:#[a-z0-9-]+)?['"]/g)) assert(existsSync(new URL('../docs'+match[1]+'index.html',import.meta.url)), 'monthly destination '+match[1]);
for(const slug of ['gensen-choshu','shakai-hoken','yukyu','column/keiri-nenkan-schedule']) {
 const html=readFileSync(new URL('../docs/'+slug+'/index.html',import.meta.url),'utf8');
 const modified=html.match(/"dateModified"\s*:\s*"([0-9-]+)"/)[1];
 assert(html.includes('更新日: <time datetime="'+modified+'"'), 'visible date agrees with JSON-LD '+slug);
}
console.log('Retention core: month boundaries, privacy, blocked storage, ICS, search, safe highlight, deterministic RSS passed');
