import {readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {validateSegments,normalize} from '../../tools/segment_claims.mjs';
const dir='reports/r16-t-tanaoroshi-hyo-a/';
const before=JSON.parse(readFileSync(dir+'units-before.json'));
const after=JSON.parse(readFileSync(dir+'units-after.json'));
const old=JSON.parse(execFileSync('git',['show','origin/main:claims/column/tanaoroshi-hyo.json'],{encoding:'utf8'}));
const ledger=JSON.parse(readFileSync('claims/column/tanaoroshi-hyo.json'));
const a=validateSegments(before,old),b=validateSegments(after,ledger);
assert.equal(b.errors.length,0);assert.equal(b.unprocessed,0);
const dom=new JSDOM(readFileSync('docs/column/tanaoroshi-hyo/index.html','utf8'));
const data=JSON.parse(dom.window.document.querySelector('script[type="application/ld+json"]').textContent);
const faq=data['@graph'].find(x=>x['@type']==='FAQPage');
const answers=[...dom.window.document.querySelectorAll('.faq-answer')].map(x=>normalize(x.textContent));
assert.deepEqual(faq.mainEntity.map(x=>normalize(x.acceptedAnswer.text)),answers);
const oc=new Set(ledger.pending_review.map(x=>x.id));assert(ledger.verified.every(x=>!oc.has(x.id)));
const concise=x=>({total:x.total,covered:x.covered,verified:x.verified,nonclaims:x.nonclaims,unprocessed:x.unprocessed,errors:x.errors});
writeFileSync(dir+'coverage-audit.json',JSON.stringify({before:concise(a),after:concise(b),pending_review_before:old.pending_review.length,pending_review_after:ledger.pending_review.length,faq_answers_equal:answers.length},null,2)+'\n');
console.log('coverage / pending-review separation / FAQ JSON-LD equality: PASS');dom.window.close();
