import fs from 'node:fs';import {execFileSync} from 'node:child_process';import {segmentClaims,validateSegments,normalize} from '../../tools/segment_claims.mjs';import {ledgerPath} from '../../tools/check_claims.mjs';
const RUN='/Users/masahiroyasu/Scripts/keiri-commander/runs/review-loop/r16/t13-a';const s=JSON.parse(fs.readFileSync(RUN+'/segments.json')),a=JSON.parse(fs.readFileSync(RUN+'/segment-adjudication.json')).segments,o=JSON.parse(fs.readFileSync(RUN+'/oc-opinion.json')).units;
const wrong=new Set(o.filter(x=>x.verdict==='wrong').map(x=>x.page+':'+x.id));const out=[],errors=[],fixed=[];let retainedOC=0;
for(const page of new Set(s.map(x=>x.page))){const units=segmentClaims(fs.readFileSync(page,'utf8'),page),m=new Map(units.map(x=>[x.id,x])),ledger=JSON.parse(fs.readFileSync(ledgerPath(page)));const c=validateSegments(units,ledger);errors.push(...c.errors.filter(x=>!x.startsWith('unprocessed segment')).map(e=>({page,error:e})));
 for(let i=0;i<s.length;i++){if(s[i].page!==page)continue;const old=s[i],d=a[i];if(d.decision==='unresolved'||wrong.has(page+':'+old.id)){const still=m.get(old.id)?.text_hash===old.text_hash;fixed.push({position:i+1,page,id:old.id,decision:d.decision,old_unit_removed_or_changed:!still});if(still)errors.push({page,id:old.id,error:'unresolved unchanged'});}
 if(d.decision==='out_of_corpus'&&!wrong.has(page+':'+old.id)){if(m.get(old.id)?.text_hash!==old.text_hash)errors.push({page,id:old.id,error:'OC changed'});else retainedOC++;if(c.links[old.id])errors.push({page,id:old.id,error:'OC incorrectly covered'});}}
 const pending=new Set(ledger.out_of_corpus.map(x=>x.id));for(const id of c.unprocessed_ids)if(!pending.has(id))errors.push({page,id,error:'unclassified'});
 out.push({page,...c,out_of_corpus:pending.size});}
fs.writeFileSync('reports/r16-t13-a/coverage-after.json',JSON.stringify(out,null,2));fs.writeFileSync('reports/r16-t13-a/fix-audit.json',JSON.stringify({fixed,retainedOC,errors},null,2));console.log({fixed:fixed.length,retainedOC,errors});if(errors.length)process.exit(1);
