from pathlib import Path
import json,subprocess,collections
W=Path.cwd();E=W/'review-evidence/auto20261002-t11-q08465';R=Path('/Users/masahiroyasu/Scripts/keiri-commander/runs/review-loop/auto20261002/t11-q08465');topics=json.loads((E/'topics.json').read_text());loc=json.loads((E/'final-locations.json').read_text());old=json.loads((E/'segments.json').read_text());adj={x['id']:x for x in json.loads((E/'segment-adjudication.json').read_text())['segments']};bef=json.loads((E/'coverage-ledger-before.json').read_text());aft=json.loads((E/'coverage-ledger-after.json').read_text());ledger=json.loads((W/'claims/column/shogaku-genka-shokyaku.json').read_text())
lines=['# auto20261002/t11-q08465 修正報告（2026-10-02）','',f'作業場: `{W}`。基点 `34be072a`。他モデル・サブエージェント・Orca・スキル・push は使用していない。入力RUNの審査・正本は読取りのみ。入力ハッシュは `review-evidence/auto20261002-t11-q08465/input-check.json`。','', '## 単位と被覆','', '| 指標 | 修正前 | 修正後 |','|---|---:|---:|',f'| 抽出単位数 | {bef["total"]} | {aft["total"]} |',f'| 台帳の主張対応（covers） | {bef["covered"]} | {aft["covered"]} |',f'| 独立照合済みの同文単位（verified） | {bef["verified"]} | {aft["verified"]} |',f'| 非主張（nonclaims） | {bef["nonclaims"]} | {aft["nonclaims"]} |',f'| check_claims --segments の未処理 | {bef["unprocessed"]} | {aft["unprocessed"]} |','| 正本外・必要資料登録 | 入力審査8 | 8（本文・ハッシュ不変） |','', '入力審査は327単位＝ok 196、nonclaim 62、out_of_corpus 8、unresolved 61（high 21 / medium 29 / low 11）。入力coverage.jsonはsol段階の235確認・73非主張・8正本外・11不明・未処理0であり、審査結果やサイト台帳の数とは別集計。','',f'修正後は主張対応{aft["covered"]}のうち独立審査okを同文で引き継げる{aft["verified"]}だけをverifiedに登録。残り{aft["covered"]-aft["verified"]}は修正者による正本照合・回答/行の対応付けで、独立再審査待ち。未処理8はすべて正本外で、専用out_of_corpus欄にneeded_source付きで残す。チェック器は正本外を独立の被覆区分として数えないため未処理に含む。正本外を除く未対応は0。','', '## 正本に照らした誤り率','', '審査のunresolved 61のうち、high/medium 50は適用条件・金額判断に関する実質誤り、low 11は質問・行名単独では断定が成立しないための保留。したがって実質wrong÷(ok+wrong)は **50÷(196+50)＝20.33%**。保留11も未解決としてwrong側に算入する保守的な管理比率は **61÷(196+61)＝23.74%**（誤り率そのものとは区別）。正本外8と非主張62は分母に含めない。','', '今回、実質誤り50単位を修正し、low 11はdata-review-context属性で数値セル・FAQ回答を同じ確認単位に含め、台帳も対応付け直した。修正者の点検で残った同論点の実質誤りは0。ただし修正後の独立誤り率は**未測定**であり、これからシェルが行うsol再照合の結果を0%と先取りしない。','', '## 論点 → 元単位ID → 全修正箇所 → 正本','', '詳細な置換前後・全出現回数は `review-evidence/auto20261002-t11-q08465/edits.json`、現在の行番号は `final-locations.json`、各論点の全IDは `topics.json`。元審査61 IDと論点IDの差集合は空。新しい説明の逐語引用・corpus_ref・scope・exceptionsは各ページのclaimsに保存し、使用正本の複製を同evidence配下corpusに置いた。','']
for name,t in topics.items():
 sev=collections.Counter(adj[i].get('severity') for i in t['ids']);lines += [f'### {name}（'+ ' / '.join(f'{k} {v}' for k,v in sev.items())+'）','', '- 元単位ID: '+', '.join('`'+i+'`' for i in t['ids']),'- 修正内容・同節例外: '+t['exceptions']]
 for page,m in loc.items():
  if name in m:lines.append('- 修正箇所: `'+page+'`'+(':'+','.join(map(str,m[name])) if m[name] else '（edits.json参照）'))
 if name=='質問行名':
  lines.append('- 修正箇所: `claims/column/shogaku-genka-shokyaku.json` の `label-<元単位ID>` 11件。表の7行名は同じ行の2制度の数値・15万円/12か月/税率30%/概算の設例に、FAQの4設問は対応回答に結合。tools/segment_claims.mjsに明示属性data-review-contextの読み取りを追加し、対象7行名・4設問は同じ行の列名と数値又は直後の回答を含む単位として再抽出した。元の表示内容・protectedを維持し、verifiedには入れていない。context-id-map.jsonに旧新11IDを記録。tests/test_segment_claims.mjsで回答・値が抜ける旧実装の赤→緑、値/回答の変更でIDが変わること、不正な文脈指定と非主張登録の拒否を確認。')
  lines.append('- 根拠: `corpus/egov_hojinzeirei_133.txt:6`、`corpus/egov_hojinzeirei_133_2.txt:6-22`、`corpus/egov_sochiho_67_5.txt:6-8`、`corpus/egov_chihozeiho_383.txt:6`、`corpus/www_tax_metro_tokyo_lg_jp_documents_d_tax_R8_shinkokutebiki_1page.txt:517-588`。個々の回答・行のrefsはlabel claimに記録。')
 else:lines.append('- 根拠: '+', '.join('`'+x+'`' for x in t['refs']))
 lines.append('')
lines += ['## 横断確認・計算機・生成物','', '- 本文・リード・まとめ・callout・比較表・仕訳・meta description/OG・SVG text/aria-label/figcaption・FAQを確認。title/OG titleは金額区分の紹介で無条件適用の断定ではなく、審査okを維持。','- 関連7ページ（対象記事、消耗品費、減価償却とは、建設仮勘定、決算整理仕訳、償却資産税、減価償却計算機）を同期。リース記事の「3年均等が使えない」は制度除外の説明で、年度月数の適用を断定していないため維持。固定資産台帳・計算機のPC4年はサーバー用除外の既存明記を確認。','- `docs/embed/genka/index.html` は計算結果注記を共有coreから描画し、今回の人数分岐修正が反映される。静的な旧人数/3年の別コピーはない。`docs/assets/genka_rates.json` は400/500/300人の新旧値・取得境界を既に保持し、誤りは参照先を固定したcore側だったため数値JSONは維持。','- `docs/assets/genka_core.js` の人数表示を取得年月で500/400人に分岐し、特定法人300人も区別。個人の一括償却注記に対象所得・供用・申告保存・対象除外を補足。`tests/boundaries/genka_core.mjs` と `tests/test_shogaku_tokurei.mjs` に2026-03/04取得の境界を追加し、条件表に登録。赤の証跡は400≠500、修正後は両境界が緑。','- `tests/stale_values.json` に500人の現行無条件使用を拒否する記録を追加。旧取得の500人は残す。','- HTMLを先にコミットし、`gen_faq_jsonld.mjs`、`gen_qa_index.mjs` と test_generators_fresh のCHECKABLE全5本を実行。FAQ JSON-LD・qa_index・column/index・sitemap・dateModifiedを同期。','', '## 正本外（書き換えなし）','']
for x in ledger['out_of_corpus']:lines += [f'- `{x["id"]}`: {x["needed_source"]}']
lines += ['', '## テスト・コミット','', '基点の赤はユーザー指定の `test_hojokin_sources`・`test_layout_visual` 2件（本作業で基点全件を再実行した実測値ではない）。PLAYWRIGHT_PATHを指定し、全テストを逐次実行。Chromiumを使う別の検査を重ねて起動していない。他セッションの完了は待っていない。自分のランナーのみ、実行中テストが終了した区切りで一時停止し、残りの横断修正・生成後に再開した。','', 'TEST_RESULTS_PENDING','', '実装コミット: `9382e9c5`、追加横展開: `7671eb3d`。最終コミットは全検証完了時に追記。pushなし。','']
(R/'fixes-applied.md').write_text('\n'.join(lines))
print('draft report',len(lines),'lines')
