import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{execFileSync}from'node:child_process';import{segmentClaims,validateSegments}from'../../tools/segment_claims.mjs';
const E='review-evidence/r16-t6-a',R='/Users/masahiroyasu/Scripts/keiri-commander/runs/review-loop/r16/t6-a';
const prev=JSON.parse(readFileSync(E+'/verification.json'));for(const[f,h]of Object.entries(prev.input_sha256))assert.equal(createHash('sha256').update(readFileSync(R+'/corpus/'+f)).digest('hex'),h,f);
const old=JSON.parse(readFileSync(R+'/segments.json')),ad=JSON.parse(readFileSync(R+'/segment-adjudication.json')).segments;const edits=JSON.parse(readFileSync(E+'/edits.json'));const ocWrong=new Set(edits.filter(x=>x.index==='oc').map(x=>x.id));
const current=[],coverage=[];for(const page of [...new Set(old.map(x=>x.page))]){const us=segmentClaims(readFileSync(page,'utf8'),page);current.push(...us);const path='claims/'+page.replace(/^docs\//,'').replace(/\/index.html$/,'.json');const ledger=JSON.parse(readFileSync(path));coverage.push({page,...validateSegments(us,ledger)});assert(ledger.unverified.every(x=>x.needed_source));}
// Match original not_wrong/unsure by exact kind/text hash, independent of positional ID suffixes.
const originals=ad.filter(x=>x.decision==='out_of_corpus').map(a=>old.find(x=>x.page===a.page&&x.id===a.id));const wrongTexts=edits.filter(x=>x.index==='oc');const preserved=originals.filter(x=>!wrongTexts.some(e=>e.page===x.page&&e.before===x.text));assert.equal(preserved.length,247);
for(const u of preserved)assert(current.some(x=>x.page===u.page&&x.kind===u.kind&&x.text_hash===u.text_hash),'changed OC '+u.id);
const result={...prev,unchanged:preserved.length,missing:[],checked_revision:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),coverage:coverage.map(({page,total,covered,verified,nonclaims,unprocessed})=>({page,total,covered,verified,nonclaims,unprocessed})),checks:{claims_changed:'claims-final.log',python:'python-tests.log',javascript:'full-tests.log',browser:'shobyo-ui.log'}};
writeFileSync(E+'/verification-final.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result.coverage));console.log('247 OC units unchanged; corpus SHA256 unchanged');
