import {execFileSync} from 'node:child_process';
import {readdirSync,writeFileSync,readFileSync} from 'node:fs';
import {browserTools,serve,contextFor,ready,DOCS} from '../../tests/layout/browser.mjs';
import {measureEmpty} from '../../tests/layout/empty-measure.mjs';
const baseline=process.argv[2]==='before';const cache=new Map();
const pages=readdirSync(DOCS,{recursive:true}).filter(f=>f==='index.html'||f.endsWith('/index.html')).map(f=>'/'+f.replace(/index.html$/,''));
const previous=process.env.RETRY?JSON.parse(readFileSync(new URL('empty-before.json',import.meta.url))):[];const jobs=[1280,390].flatMap(width=>pages.map(url=>({url,width}))).filter(j=>!process.env.RETRY||previous.some(r=>r.error&&r.url===j.url&&r.width===j.width));let next=0;const results=previous.filter(r=>!r.error);
const {chromium}=await browserTools(),server=await serve(),browser=await chromium.launch();
try{await Promise.all(Array.from({length:1},async()=>{const c=await contextFor(browser,server.origin),p=await c.newPage();if(baseline)await c.route(server.origin+'/**',route=>{const u=new URL(route.request().url());let f='docs'+decodeURIComponent(u.pathname);if(f.endsWith('/'))f+='index.html';if(/\.(html|css|js)$/.test(f)){if(!cache.has(f)){try{cache.set(f,execFileSync('git',['show','HEAD:'+f],{maxBuffer:20*1024*1024}));}catch{cache.set(f,null);}}const body=cache.get(f);if(body)return route.fulfill({body,contentType:f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':'application/javascript'});}return route.continue();});while(next<jobs.length){const j=jobs[next++];await p.setViewportSize({width:j.width,height:900});try{await ready(p,server.origin+j.url);const issues=await p.evaluate(measureEmpty);results.push({...j,issues});if(issues.length)await p.screenshot({path:'reports/uiux-0927/'+(baseline?'before':'after')+'-empty-'+j.url.replaceAll('/','_')+'-'+j.width+'.png',fullPage:true});}catch(e){results.push({...j,error:String(e)});}if(next%100===0)console.log(next);}await c.close();}));}finally{await browser.close();server.close();}
writeFileSync(new URL(`empty-${process.argv[2]||'before'}.json`,import.meta.url),JSON.stringify(results,null,2));console.log(JSON.stringify(results.filter(r=>r.error||r.issues.length),null,2));
