import {execFileSync} from 'node:child_process';import {writeFileSync,mkdirSync} from 'node:fs';
import {browserTools,serve,contextFor,ready} from '../../tests/layout/browser.mjs';import {measureEmpty} from '../../tests/layout/empty-measure.mjs';
const phase=process.argv[2],before=phase==='before',out='reports/uiux-0927/'+phase+'/evidence';mkdirSync(out,{recursive:true});
const jobs=[['/zengin-kana/','#copyErr'],['/yakuin-shataku/','#menseki-note'],['/column/shisanhyo-mikata/','section.related'],['/column/shukkin-denpyo/','section.related'],['/tedori/','table:has(td:has-text("＋20,000円"))'],['/iryohi/','.card'],['/column/denchoho-kensaku-yoken/','.next-read'],['/column/denchoho-wakariyasuku/','.next-read']];
const {chromium}=await browserTools(),server=await serve(),browser=await chromium.launch(),rows=[],cache=new Map();
try{for(const width of [1280,390]){const c=await contextFor(browser,server.origin,width);await c.route(server.origin+'/**',route=>{
 const u=new URL(route.request().url());if(u.pathname.endsWith('/shataku_r08.json'))return route.fulfill({status:404,body:'failure fixture'});
 let f='docs'+decodeURIComponent(u.pathname);if(f.endsWith('/'))f+='index.html';if(before&&/\.(html|css|js)$/.test(f)){if(!cache.has(f)){try{cache.set(f,execFileSync('git',['show','8ae8be5e8f5404b24ec521463e5e4fb7bd2f7013:'+f],{maxBuffer:20*1024*1024}));}catch{cache.set(f,null);}}const body=cache.get(f);if(body)return route.fulfill({body,contentType:f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':'application/javascript'});}return route.continue();});
 const p=await c.newPage();for(const [url,selector]of jobs){await ready(p,server.origin+url);let loc=p.locator(selector).first();const exists=await loc.count();let rect=null;if(exists){rect=await loc.boundingBox();if(rect)await p.evaluate(y=>scrollTo(0,Math.max(0,y-300)),rect.y);}else await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));
 const path=out+'/'+url.replaceAll('/','_')+'-'+width+'.png';await p.screenshot({path});const measures=await p.evaluate(()=>({pageHeight:document.documentElement.scrollHeight,cardTop:document.querySelector('main>.card')?.getBoundingClientRect().top+scrollY,related:[...document.querySelectorAll('.next-read .tool-card')].map(e=>({visible:e.checkVisibility(),href:e.getAttribute('href')}))}));rows.push({url,width,selector,exists,rect,issues:await p.evaluate(measureEmpty),image:path,...measures});}
 await c.close();}}finally{await browser.close();server.close();}writeFileSync(out+'/metrics.json',JSON.stringify(rows,null,2));
