import {readdirSync,writeFileSync} from 'node:fs';
import {browserTools,serve,contextFor,ready,DOCS} from '../../tests/layout/browser.mjs';
import {measure} from '../../tests/layout/measure.mjs';
const phase=process.argv[2]||'before',widths=phase==='before'?[1280,390]:[1280,1536,1920,1200,768,390];
const paths=readdirSync(DOCS,{recursive:true}).filter(f=>f==='index.html'||f.endsWith('/index.html')).sort().map(f=>'/'+f.replace('index.html',''));
const {chromium}=await browserTools(),server=await serve(),browser=await chromium.launch();let rows=[],next=0;
const jobs=widths.flatMap(width=>paths.map(url=>({url,width})));
try{await Promise.all(Array.from({length:1},async()=>{const c=await contextFor(browser,server.origin),p=await c.newPage();while(next<jobs.length){let j=jobs[next++];try{await p.setViewportSize({width:j.width,height:j.width===1536?864:j.width===1920?1080:j.width===1200?800:j.width===768?1024:j.width===390?844:900});await ready(p,server.origin+j.url);const m=await p.evaluate(measure);const extra=await p.evaluate(()=>{
 const vis=e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden';const rgb=s=>(s.match(/[\d.]+/g)||[]).map(Number),lum=c=>c.slice(0,3).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4}).reduce((s,x,i)=>s+x*[.2126,.7152,.0722][i],0);
 let contrast=[];for(const e of document.querySelectorAll('main *, .wrap *')){if(!vis(e)||!e.textContent.trim()||!Array.from(e.childNodes).some(n=>n.nodeType===3&&n.textContent.trim())||e.closest('svg,script,style,.pr-block')||['OPTION'].includes(e.tagName))continue;const cs=getComputedStyle(e),fg=rgb(cs.color);let bg=[255,255,255],n=e;while(n){const v=rgb(getComputedStyle(n).backgroundColor);if(v.length===3||v[3]===1){bg=v;break;}n=n.parentElement;}const ratio=(Math.max(lum(fg),lum(bg))+.05)/(Math.min(lum(fg),lum(bg))+.05),required=parseFloat(cs.fontSize)>=24||(parseFloat(cs.fontSize)>=18.66&&+cs.fontWeight>=700)?3:4.5;if(ratio<required-.03&&!e.matches(':disabled'))contrast.push({tag:e.tagName,cls:e.className,text:e.textContent.trim().slice(0,90),color:cs.color,bg,ratio});}
 return {small:[...document.querySelectorAll('button,summary,a[role=button]')].filter(vis).map(e=>({tag:e.tagName,cls:e.className,text:e.textContent.trim().slice(0,75),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})).filter(e=>e.h<43.9||e.w<43.9),contrast:contrast.slice(0,30)};
});let print=[];if(j.width===1280){await p.emulateMedia({media:'print'});print=await p.evaluate(()=>[...document.querySelectorAll('.scroll-wrap,.fee-scroll,.retention-table')].filter(e=>e.getClientRects().length&&e.scrollHeight>e.clientHeight+2&&['auto','hidden','scroll','clip'].includes(getComputedStyle(e).overflowY)).map(e=>({id:e.id,cls:e.className,h:e.clientHeight,sh:e.scrollHeight,text:e.textContent.trim().slice(0,100)})));await p.emulateMedia({media:'screen'});}rows.push({...j,...m,...extra,print});if(rows.length%100===0)console.log(rows.length+'/'+jobs.length);
}catch(e){rows.push({...j,error:String(e)});}}await c.close();}));}finally{await browser.close();server.close();writeFileSync(`reports/uiux-0927/sweep-${phase}.json`,JSON.stringify(rows,null,2));}console.log('DONE',rows.length);
