// 2026-09-29 一次資料を再取得して審査。期待値は条文・公表表から独立に計算。
import { calcJidoshazei } from "../../docs/assets/jidoshazei_core.js";
import { readFileSync } from "node:fs";
const load = f => JSON.parse(readFileSync(new URL(`../../docs/assets/${f}`, import.meta.url)));
const D = load("jidoshazei_r08.json");
export const cases = [
  { name: "軽・2015年3月の旧税率7,200円は四輪以上に限定", run: () => { const r=calcJidoshazei({vehicle:'kei',fuel:'gasoline',firstReg:'2015-03'},D); return r.annual===7200 && r.ccLabel.includes('四輪以上') && !r.vehicleName.includes('三輪以上'); }, expected:true, source:"https://www.city.osaka.lg.jp/zaisei/page/0000587096.html", quote:"4輪以上のもので、総排気量660cc以下のもの" },
  { name: "軽・2015年4月の新税率10,800円は四輪以上に限定", run: () => { const r=calcJidoshazei({vehicle:'kei',fuel:'gasoline',firstReg:'2015-04'},D); return r.annual===10800 && r.ccLabel.includes('四輪以上') && !r.vehicleName.includes('三輪以上'); }, expected:true, source:"https://www.city.osaka.lg.jp/zaisei/page/0000587096.html", quote:"4輪以上のもので、総排気量660cc以下のもの" },
  { name: "3月新規登録0円の説明は翌4月1日の所有と軽課等を条件にする", run: () => { const r=calcJidoshazei({vehicle:'passenger',cc:'ev',fuel:'ev_other',firstReg:'2025-03',prorateMonth:3},D); return r.dueThisYear===0 && r.notes.some(n=>n.includes('翌年度4月1日') && n.includes('軽課') && n.includes('抹消登録')); }, expected:true, source:"https://laws.e-gov.go.jp/api/2/law_data/325AC0000000226", quote:"自動車税の賦課期日は、四月一日とする。" },
  { name: "4月新規登録の月割説明も翌年度の税額を無条件に断定しない", run: () => { const r=calcJidoshazei({vehicle:'passenger',cc:'ev',fuel:'ev_other',firstReg:'2025-04',prorateMonth:4},D); return r.dueThisYear===22900 && r.notes.some(n=>n.includes('翌年度4月1日') && n.includes('軽課') && n.includes('抹消登録')); }, expected:true, source:"https://laws.e-gov.go.jp/api/2/law_data/325AC0000000226", quote:"自動車税の賦課期日は、四月一日とする。" },
  { name: "重課出力・登録車ディーゼル11年の基準日は4月1日", run: () => { const r=calcJidoshazei({vehicle:'passenger',cc:'le2000',fuel:'diesel',firstReg:'2015-03',jyuka:true},D); return r.annual===45400 && r.notes.some(n=>n.includes('4月1日現在') && n.includes('11年')); }, expected:true, source:"https://www.tax.metro.tokyo.lg.jp/kazei/automobiles/shubetsu", quote:"4月1日現在、初回新規登録後" },
  { name: "重課出力・軽の13年経過日の翌年度開始", run: () => { const r=calcJidoshazei({vehicle:'kei',fuel:'gasoline',firstReg:'2012-06',jyuka:true},D); return r.annual===12900 && r.notes.some(n=>n.includes('13年経過日の翌年度以降')); }, expected:true, source:"https://www.city.osaka.lg.jp/zaisei/page/0000587096.html", quote:"当該13年を経過した日の翌年度分の軽自動車税から重課税率を適用します" },
  { name: "登録車・2019年9月初度登録・1,000cc以下は旧税率29,500円", run: () => (calcJidoshazei({vehicle:'passenger',cc:'le1000',fuel:'gasoline',firstReg:'2019-09'}, D).annual), expected: 29500, source: "https://www.pref.mie.lg.jp/common/content/001128502.pdf", quote: "1.0㍑以下 7,500 2,000 8,600 25,000 6,500 29,500 33,900 1.0㍑超" },
  { name: "登録車・2019年10月初度登録・1,000cc以下は新税率25,000円", run: () => (calcJidoshazei({vehicle:'passenger',cc:'le1000',fuel:'gasoline',firstReg:'2019-10'}, D).annual), expected: 25000, source: "https://www.pref.mie.lg.jp/common/content/001128502.pdf", quote: "1.0㍑以下 7,500 2,000 8,600 25,000 6,500 29,500 33,900 1.0㍑超" },
  { name: "2月新規登録は翌月の3月分1か月、25,000円年額なら2,000円", run: () => (calcJidoshazei({vehicle:'passenger',cc:'le1000',fuel:'gasoline',firstReg:'2019-10',prorateMonth:2}, D).dueThisYear), expected: 2000, source: "https://www.tax.metro.tokyo.lg.jp/kazei/car_shubetsu.html", quote: "登録の月の翌月から年度末までの月数による課税 消滅 ＜廃 車＞ 月割課税 ４月から消滅（抹消登録）の月までの月数による課税 変更 ＜所有者変更＞＜転出＞＜転入＞ 東京都ナンバー ⇄ 東京都ナンバー ⇄ 東京都ナンバー ⇄ 他道府県ナンバー ⇄ 年課税 ４月１日現在の所有者にその年度分を全額課税 ＊ 新規登録の場合、自動車税事務所等の窓口にて、直接納めます。 ＊＊ 税率表 の年額 × 課税される月数/12 ＝ 税額 （100円未満切捨て）" },
  { name: "3月新規登録は当年度の課税月0か月で0円", run: () => (calcJidoshazei({vehicle:'passenger',cc:'le1000',fuel:'gasoline',firstReg:'2019-10',prorateMonth:3}, D).dueThisYear), expected: 0, source: "https://www.tax.metro.tokyo.lg.jp/kazei/car_shubetsu.html", quote: "登録の月の翌月から年度末までの月数による課税" },
  { name: "令和8年度の出力の税目名は旧称（種別割）を使わない", run: () => { const p=calcJidoshazei({vehicle:'passenger',cc:'le2000',fuel:'gasoline',firstReg:'2019-10',prorateMonth:8},D); const k=calcJidoshazei({vehicle:'kei',fuel:'gasoline',firstReg:'2015-04',prorateMonth:6},D); return [p,k].every(r=>!r.taxKind.includes('種別割') && r.notes.every(n=>!n.includes('種別割'))) && p.taxKind.startsWith('自動車税') && k.taxKind.startsWith('軽自動車税'); }, expected:true, source:"https://www.tax.metro.tokyo.lg.jp/kazei/automobiles/shubetsu", quote:"令和8年4月1日より、自動車税種別割は自動車税へ名称が変更されました。" },
];
