// 2026-09-29 一次資料を再取得して審査。期待値は条文・公表表から独立に計算。
import { shikyuNissu, keizokuKyufu, calcShobyo } from "../../docs/assets/shobyo_core.js";
import { readFileSync } from "node:fs";
const D=JSON.parse(readFileSync(new URL("../../docs/assets/shobyo_r08.json",import.meta.url)));
export const cases = [
  { name: "待期3日境界の1日下（休業2日）", run: () => (shikyuNissu(2, false)), expected: 0, source: "https://laws.e-gov.go.jp/api/2/law_data/211AC0000000070?response_format=xml", quote: "その労務に服することができなくなった日から起算して三日を経過した日から労務に服することができない期間、傷病手当金を支給する。" },
  { name: "待期3日境界の1日上（休業4日）", run: () => (shikyuNissu(4, false)), expected: 1, source: "https://laws.e-gov.go.jp/api/2/law_data/211AC0000000070?response_format=xml", quote: "その労務に服することができなくなった日から起算して三日を経過した日から労務に服することができない期間、傷病手当金を支給する。" },
  { name: "資格喪失後継続給付の1年要件の1月下（11月）", run: () => (keizokuKyufu({hihokenshaMonths:11, receivingAtLoss:true}).ok), expected: false, source: "https://laws.e-gov.go.jp/api/2/law_data/211AC0000000070?response_format=xml", quote: "被保険者の資格を喪失した日（任意継続被保険者の資格を喪失した者にあっては、その資格を取得した日）の前日まで引き続き一年以上被保険者（任意継続被保険者又は共済組合の組合員である被保険者を除く。）であった者（第百六条において「一年以上被保険者であった者」という。）であって、その資格を喪失した際に傷病手当金又は出産手当金の支給を受けているものは、被保険者として受けることができるはずであった期間、継続して同一の保険者からその給付を受けることができる。" },
  { name: "資格喪失後継続給付の1年要件の1月上（13月）", run: () => (keizokuKyufu({hihokenshaMonths:13, receivingAtLoss:true}).ok), expected: true, source: "https://laws.e-gov.go.jp/api/2/law_data/211AC0000000070?response_format=xml", quote: "被保険者の資格を喪失した日（任意継続被保険者の資格を喪失した者にあっては、その資格を取得した日）の前日まで引き続き一年以上被保険者（任意継続被保険者又は共済組合の組合員である被保険者を除く。）であった者（第百六条において「一年以上被保険者であった者」という。）であって、その資格を喪失した際に傷病手当金又は出産手当金の支給を受けているものは、被保険者として受けることができるはずであった期間、継続して同一の保険者からその給付を受けることができる。" },
  { name: "t6 通算549日・既受給548", run: () => (calcShobyo({startDate:'2022-03-04',standards:Array(12).fill(300000),restDays:30,taikiDone:true,usedDays:548},D).days), expected: 1, source: "https://laws.e-gov.go.jp/law/211AC0000000070", quote: "傷病手当金の支給期間は、同一の疾病又は負傷及びこれにより発した疾病に関しては、その支給を始めた日から通算して一年六月間とする。" },
  { name: "t6 通算549日・既受給549", run: () => (calcShobyo({startDate:'2022-03-04',standards:Array(12).fill(300000),restDays:30,taikiDone:true,usedDays:549},D).days), expected: 0, source: "https://laws.e-gov.go.jp/law/211AC0000000070", quote: "傷病手当金の支給期間は、同一の疾病又は負傷及びこれにより発した疾病に関しては、その支給を始めた日から通算して一年六月間とする。" },
  { name: "t6 通算549日・既受給550", run: () => (calcShobyo({startDate:'2022-03-04',standards:Array(12).fill(300000),restDays:30,taikiDone:true,usedDays:550},D).days), expected: 0, source: "https://laws.e-gov.go.jp/law/211AC0000000070", quote: "傷病手当金の支給期間は、同一の疾病又は負傷及びこれにより発した疾病に関しては、その支給を始めた日から通算して一年六月間とする。" },
  { name: "t6 終了日は通算日数だけでは確定しない", run: () => (calcShobyo({startDate:'2022-03-04',standards:Array(12).fill(300000),restDays:30,taikiDone:true,usedDays:100},D).kikan.end), expected: null, source: "https://laws.e-gov.go.jp/law/211AC0000000070", quote: "傷病手当金の支給期間は、同一の疾病又は負傷及びこれにより発した疾病に関しては、その支給を始めた日から通算して一年六月間とする。" },
  { name: "t6 中断後は既受給100日と今回30日だけを消費", run: () => (calcShobyo({startDate:'2022-03-04',standards:Array(12).fill(300000),restDays:30,taikiDone:true,usedDays:100},D).kikan.remainingAfter), expected: 419, source: "https://laws.e-gov.go.jp/law/211AC0000000070", quote: "傷病手当金の支給期間は、同一の疾病又は負傷及びこれにより発した疾病に関しては、その支給を始めた日から通算して一年六月間とする。" },
  { name: "t6 既受給者から待期3日を再控除しない", run: () => (calcShobyo({startDate:'2022-03-04',standards:Array(12).fill(300000),restDays:30,usedDays:100},D).days), expected: 30, source: "https://laws.e-gov.go.jp/law/211AC0000000070", quote: "傷病手当金の支給期間は、同一の疾病又は負傷及びこれにより発した疾病に関しては、その支給を始めた日から通算して一年六月間とする。" },
  ...[11,12].map(months=>({name:`r16 日額3か月と継続給付${months}か月を分離`,run:()=>calcShobyo({startDate:'2026-09-01',monthly:500000,months:3,continuationMonths:months,taishokugo:true,taikiDone:true,restDays:30},D).eligible,expected:months===12,source:'https://laws.e-gov.go.jp/law/211AC0000000070',quote:'被保険者の資格を喪失した日（任意継続被保険者の資格を喪失した者にあっては、その資格を取得した日）の前日まで引き続き一年以上被保険者'})),
  {name:'r16 継続給付12か月でも日額は現保険者3か月の上限',run:()=>calcShobyo({startDate:'2026-09-01',monthly:500000,months:3,continuationMonths:12,taishokugo:true,taikiDone:true,restDays:30},D).nichigaku,expected:7113,source:'https://www.kyoukaikenpo.or.jp/benefit/injury_and_sickness_allowance/',quote:'支給開始日以前の期間が12か月に満たない場合'},
  {name:'r16 継続給付月数未確認は判定を止める',run:()=>calcShobyo({startDate:'2026-09-01',monthly:300000,months:12,continuationMonths:null,taishokugo:true,restDays:30},D).reason,expected:'no_continuation_months',source:'https://laws.e-gov.go.jp/law/211AC0000000070',quote:'被保険者の資格を喪失した日（任意継続被保険者の資格を喪失した者にあっては、その資格を取得した日）の前日まで引き続き一年以上被保険者'},
];
