// 2026-09-29 一次資料を再取得して審査。期待値は条文・公表表から独立に計算。
import { combinedPremiumPct, calcZangyodai } from "../../docs/assets/zangyodai_core.js";
import { readFileSync } from "node:fs";
const load = f => JSON.parse(readFileSync(new URL(`../../docs/assets/${f}`, import.meta.url)));
const D = load("zangyodai_rates.json");
export const cases = [
  { name: "月60時間境界の1分下（59時間59分）は全時間125%", run: () => (calcZangyodai({base:196000,annualHolidays:120,dailyHours:8,overtimeHours:59+59/60,holidayHours:0,nightHours:0,fixedAmount:0}, D).total), expected: 89975, source: "https://laws.e-gov.go.jp/api/2/law_data/322AC0000000049?response_format=xml", quote: "当該延長して労働させた時間が一箇月について六十時間を超えた場合においては、その超えた時間の労働については、通常の労働時間の賃金の計算額の五割以上" },
  { name: "月60時間境界の1分上（60時間1分）は超過1分だけ150%", run: () => (calcZangyodai({base:196000,annualHolidays:120,dailyHours:8,overtimeHours:60+1/60,holidayHours:0,nightHours:0,fixedAmount:0}, D).total), expected: 90030, source: "https://laws.e-gov.go.jp/api/2/law_data/322AC0000000049?response_format=xml", quote: "当該延長して労働させた時間が一箇月について六十時間を超えた場合においては、その超えた時間の労働については、通常の労働時間の賃金の計算額の五割以上" },
  { name: "時間外1時間と深夜1時間が重なると上乗せ率合計50%", run: () => (combinedPremiumPct("overtime", true, D)), expected: 50, source: "https://laws.e-gov.go.jp/api/2/law_data/322M40000100023?response_format=xml", quote: "第二十条 法第三十三条又は法第三十六条第一項の規定によつて延長した労働時間が午後十時から午前五時（厚生労働大臣が必要であると認める場合は、その定める地域又は期間については午後十一時から午前六時）までの間に及ぶ場合においては、使用者はその時間の労働については、第十九条第一項各号の金額にその労働時間数を乗じた金額の五割以上（その時間の労働のうち、一箇月について六十時間を超える労働時間の延長に係るものについては、七割五分以上）の率で計算した割増賃金を支払わなければならない。 法第三十三条又は法第三十六条第一項の規定による休日の労働時間が午後十時から午前五時（厚生労働大臣が必要であると認める場合は、その定める地域又は期間については午後十一時から午前六時）までの間に及ぶ場合においては、使用者はその時間の労働については、前条第一項各号の金額にその労働時間数を乗じた金額の六割以上" },
  { name: "60時間超の時間外と深夜が重なると上乗せ率合計75%", run: () => (combinedPremiumPct("overtime_over60", true, D)), expected: 75, source: "https://laws.e-gov.go.jp/api/2/law_data/322M40000100023?response_format=xml", quote: "一箇月について六十時間を超える労働時間の延長に係るものについては、七割五分以上" },
  { name: "法定休日と深夜が重なると上乗せ率合計60%", run: () => (combinedPremiumPct("holiday", true, D)), expected: 60, source: "https://laws.e-gov.go.jp/api/2/law_data/322M40000100023?response_format=xml", quote: "第二十条 法第三十三条又は法第三十六条第一項の規定によつて延長した労働時間が午後十時から午前五時（厚生労働大臣が必要であると認める場合は、その定める地域又は期間については午後十一時から午前六時）までの間に及ぶ場合においては、使用者はその時間の労働については、第十九条第一項各号の金額にその労働時間数を乗じた金額の五割以上（その時間の労働のうち、一箇月について六十時間を超える労働時間の延長に係るものについては、七割五分以上）の率で計算した割増賃金を支払わなければならない。 法第三十三条又は法第三十六条第一項の規定による休日の労働時間が午後十時から午前五時（厚生労働大臣が必要であると認める場合は、その定める地域又は期間については午後十一時から午前六時）までの間に及ぶ場合においては、使用者はその時間の労働については、前条第一項各号の金額にその労働時間数を乗じた金額の六割以上" },
  { name: "所定内深夜1時間は通常賃金を重ねず25%分だけ", run: () => (calcZangyodai({base:196000,annualHolidays:120,dailyHours:8,overtimeHours:0,holidayHours:0,nightHours:1,fixedAmount:0}, D).total), expected: 300, source: "https://laws.e-gov.go.jp/api/2/law_data/322AC0000000049?response_format=xml", quote: "その時間の労働については、通常の労働時間の賃金の計算額の二割五分以上の率で計算した割増賃金を支払わなければならない。" },
  { name: "法定休日1時間は通常賃金込み135%", run: () => (calcZangyodai({base:196000,annualHolidays:120,dailyHours:8,overtimeHours:0,holidayHours:1,nightHours:0,fixedAmount:0}, D).total), expected: 1620, source: "https://laws.e-gov.go.jp/api/2/law_data/406CO0000000005?response_format=xml", quote: "労働させた休日の労働については三割五分とする" },
  { name: "60時間の前後を別々に丸めず、時間外労働の月総額を1回だけ円単位処理する", run: () => (calcZangyodai({base:100000,annualHolidays:120,dailyHours:8,overtimeHours:60+1/60,holidayHours:0,nightHours:0,fixedAmount:0}, D).total), expected: 45934, source: "https://jsite.mhlw.go.jp/aichi-roudoukyoku/var/rev0/0119/6636/hasuutoriatukai.pdf", quote: "１か月における時間外労働、休日労働、深夜業の各々の割増賃金の総額に１円未満の端数が生じた場合、（２）と同様に処理すること。" },
];
